FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build -- --configuration=production


FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=production

# copiar build
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package*.json ./

RUN npm ci --omit=dev

EXPOSE 4200

# iniciar servidor SSR
CMD ["node", "dist/minialura/server/server.mjs"]
